spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolhub
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    type : com.mchange.v2.c3p0.ComboPooledDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083
