spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/schoolhub
    username: prod_user
    password: ${PROD_DB_PASSWORD}  # Use env var in prod!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type :  org.apache.commons.dbcp2.BasicDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
