spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolhub
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    type : com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
